FROM node:22.14.0-bookworm-slim AS base

COPY ./app/package.json .
RUN corepack enable

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm i
ADD ./app .

ENV NODE_ENV="production"
RUN pnpm run build

FROM base as production
COPY --from=build ./build ./build
COPY --from=build ./package.json .

ENV PORT="3000"
ENV NODE_ENV="production"
ENV ORIGIN="https://localhost"

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm i

EXPOSE 3000
